export interface Essay {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  content: string;
}

export const essays: Essay[] = [
  {
    id: "ai-didnt-break-literacy",
    title: "AI Didn't Break Literacy, We Did",
    excerpt: "Long before ChatGPT entered classrooms, literacy was already in decline. The tools simply revealed the fractures already there.",
    date: "Apr 2026",
    readTime: "12 min",
    content: `In 2026, students use AI voraciously. But long before ChatGPT entered classrooms, literacy was already in decline.

When I ran a tutoring company with over 500 students, I saw nine-year-olds submit writing homework entirely generated by AI. Parents could not believe their children knew how to use AI, and students, for the most part, felt clever. But what I saw beneath the surface was not an AI problem, it was a literacy one. The tools simply revealed the fractures already there.

Do Not Blame the Robots

AI may be a convenient scapegoat, but it does not explain the data. In 2022, only 26% of U.S. eighth graders were proficient in writing. Reading scores have been falling steadily for more than a decade. The truth is, we lost our grip on literacy long before students had access to chatbots.

What Is Really Going On

The underlying causes are complex:

• Children are immersed in an attention economy. Reading and writing compete with infinite scroll platforms optimised for compulsive interaction. Between TikTok, Roblox and YouTube Shorts, sustained engagement with complex ideas is increasingly rare.
• Students are exposed primarily to short-form, low-complexity inputs such as captions, comments, scripts and chat. The result is a constriction of syntax, reduced lexical diversity and a weakening of abstract reasoning.
• Assigned reading is often avoided. Students outsource comprehension to summaries or AI tools. If the work is not meaningful or connected to their world, there is no intrinsic reason to persist through cognitive friction.

The Cost of Letting It Slide

When students stop reading deeply and writing critically, the downstream effects accumulate:

• They struggle to form, retain and articulate complex thought.
• They become passive consumers in systems that reward clarity and synthesis.
• They hit a glass ceiling they cannot describe because they lack the linguistic tools to name it.
• They grow increasingly reliant on generative systems to scaffold expression, leading to convergence on median linguistic forms controlled by a few foundational models.

AI as a Normalisation Engine

Generative models, by design, predict the most statistically likely output. In doing so, they flatten originality. Students who depend on AI to write are not developing fluency. They are curating from averages. This results in stylistic homogenisation and a diminished capacity to reason beyond the frame of the prompt.

Why Writing Still Matters in the Age of AI

Writing is not just transcription. It is the act of thinking on the page. It forces synthesis, prioritisation and judgment. Even in a world where LLMs draft fluid text, those who write well will retain an edge. They will know how to shape a prompt, how to iterate and how to decide what is worth saying. Writing is not obsolete. It is becoming a meta-skill.

Reclaiming Literacy in the Attention Economy

We do not need more gamification. We need more meaning.
Real engagement is not built on dopamine loops. It is built on relevance.
That means designing literacy experiences that connect to students' interests and communities, and then stretch them into complexity. Personal expression, authentic audience and voice are not luxuries. They are the gateway to deeper learning.

Rethinking Assessment for a Post-AI World

Assessments shape habits. If we want original thinkers, we must assign tasks that cannot be easily completed by language models. These include:

• Context-rich writing grounded in personal experience
• Open-ended argumentation with unpredictable structure
• Projects that reward novelty, ambiguity and divergent thinking

When AI is useful, such as for planning, ideation or rephrasing, we should teach students how to use it critically rather than blindly. Not as a replacement, but as a tool to extend their reach.

Rebuilding Writing Instruction at Scale

Writing is cognitively demanding. It is slow, recursive and difficult to standardise. This is why it was sidelined during pandemic-era instruction in favour of subjects more easily assessed.

But writing is also where reasoning is made visible. We need tools and approaches that:

• Model expert composition processes
• Provide formative feedback on syntax, structure and clarity
• Adapt to diverse entry points and skill levels

Unlike mathematics, English has no single knowledge graph. Diagnostic literacy tools must reflect this by measuring not binary right or wrong answers, but gradients of progress in coherence, argument and rhetorical control.

Defining Literacy for 2030

Literacy now includes:

• Deep reading and critical consumption of generated content
• Generative fluency, meaning the ability to collaborate with AI without ceding authorship
• Writing with clarity, originality and audience awareness in a hybrid human–machine world

These are not skills we can afford to leave undeveloped.

The Path Forward

Blaming AI for a crisis it did not create obscures what really happened.
We let literacy drift. We stripped it of purpose, pressure-tested it under outdated metrics and failed to connect it to the world students actually live in.

If we want a generation that can think clearly, argue with nuance and write with power, we must treat literacy not as a subject but as infrastructure.
Because reclaiming literacy is not about resisting technology.
It is about remembering why writing ever mattered in the first place.`,
  },
  {
    id: "buying-my-second-house-at-19",
    title: "Buying My Second House at 19",
    excerpt: "Australian banks need a 10% deposit. I had $1,000. This taught me to test assumptions and push relentlessly.",
    date: "Mar 2026",
    readTime: "5 min",
    content: `At 19, I was juggling a university degree, an investment banking internship and a tutoring business I had built to support my family. I had $1,000 in the bank. And I decided to buy an $888,000 house.

The Background

I had already bought my first property earlier that year. The original plan was to purchase the neighbouring lot as well, but that deal fell through. Instead of retreating, I started looking for something bigger. I was tired of feeling like I was working around the clock just to keep my family afloat. I wanted to build wealth for myself, not just earn an income.

I knew I could service the mortgage. My tutoring business was generating strong cashflow. But the business was still early, and banks do not lend based on potential. Traditional finance requires years of documented income, established credit history and conventional employment. I had none of that on paper, even though the money was there every month.

The problem was not affordability. It was legibility. Australian banks typically require a 10% deposit plus stamp duty. On an $888k property, that is roughly $100,000 upfront. I had one per cent of that.

Nobody Took Me Seriously

When I started calling agents, vendors and brokers, most did not take me seriously. I was 19. I had no substantial savings. I looked, on paper, like someone who had no business being in the conversation.

I heard every version of no. Too young. Not enough capital. Come back in a few years. Some people were polite about it. Others were not.

But I kept calling. I believed the 10% deposit was a convention, not a hard rule. If I could find people willing to think creatively, there might be a structure that worked.

Finding the Right People

After dozens of calls, I found a broker, a solicitor and an accountant who were willing to work with me. They did not dismiss the idea. They asked how we could make it work.

Together, we structured the deal around a refinance of my first property. The equity I had built allowed us to effectively finance the entire purchase, including stamp duty, without the standard deposit. It was unconventional, but it was legitimate. The key was finding professionals who understood that rules have more flexibility than most people assume.

Friday, Saturday, Monday

Once the team was in place, everything moved fast. I was approved on Friday, inspected the property on Saturday and signed on Monday. Three days from approval to contract. No hesitation.

What I Learned

Most people assume the barrier to entry is financial. In my case, the real barrier was social. It was the assumption, held by nearly everyone I spoke to, that someone my age could not and should not be doing this.

The lesson was not about property. It was about testing assumptions. When you hear no repeatedly, you learn to distinguish between a hard constraint and a soft one. Most barriers are not walls. They are doors that nobody has tried opening from the right angle.`,
  },
  {
    id: "why-i-decided-to-risk-it-all",
    title: "Why I Decided to Risk It All",
    excerpt: "Leaving a tutoring business doing $500k ARR and selling all property. Sunk cost, the region beta paradox, and choosing growth over comfort.",
    date: "Feb 2026",
    readTime: "7 min",
    content: `I walked away from a tutoring business doing $500k in annual recurring revenue. I sold all my property. From the outside, it looked irrational. From the inside, it was the clearest decision I have ever made.

The Slow Build-Up

It was not a single moment. It was a feeling that accumulated over months, sharpened by certain experiences I could not unsee.

During a winter internship in San Francisco, I met people my age who were building at a completely different scale. Peers getting into Y Combinator. Friends raising money on Shark Tank. Founders who were ambitious, talented and relentless. It was not jealousy. It was a yearning. I wanted to be part of that world, and I knew I never would be if I kept running tutoring centres in suburban Australia.

I came home and looked at what I had built. It was good. It was stable. It was growing. And I felt nothing.

The Region Beta Paradox

There is a concept called the region beta paradox. It describes how moderate discomfort is harder to escape than extreme pain, because it never triggers the urgency to change. If the business had been failing, the decision would have been easy. But it was succeeding, and that made it harder.

I was comfortable. I could see the next five years clearly. More tutoring centres, more property, more of the same. And that clarity terrified me. I could not see myself being happy. I could not see myself being more fulfilled. I was optimising for a life I did not want.

I was bored. Not in the shallow sense, but in the deep sense of knowing that I was capable of more and choosing not to pursue it.

Sunk Cost

The sunk cost was real. Years of work, relationships, reputation, all built around a model I had outgrown. Letting go of that felt like erasing part of my identity. I had built this business from my living room as a university freshman to support my family. It had grown to four locations. It had changed the trajectory of hundreds of students.

But sunk cost is a trap precisely because it feels like value. It is not. It is weight. The time I had already invested was gone regardless. The only question that mattered was whether I wanted to spend the next five years the same way I had spent the last three.

The Hardest Part

The hardest thing to let go of was not the money or the status. It was the people. Students who relied on the program. Families who trusted me. A team I had trained and led. Walking away from them felt like a betrayal, even though I knew intellectually that the business could continue without me.

I handed the reigns to my younger brother. He was capable, committed and ready. But the guilt of stepping back from something so personal was heavier than I expected.

Everyone Thought I Was Crazy

When I told people what I was doing, most thought I had lost my mind. Why would you leave something that is working? Why would you sell your properties? Why would you give up $500k a year at your age?

I understood the logic. From the outside, I was throwing away everything I had built. But I had already done the math on what staying looked like, and the cost of comfort was higher than the cost of uncertainty.

What I Walked Into

I did not have a master plan. I was exploring multiple directions simultaneously, trying to find the problem that would stretch me the way the tutoring business once had. I wanted to build things at a larger scale. I wanted to work in technology. I wanted to be around people who made me feel like I was just getting started, not winding down.

The Trade

Security for growth. Comfort for uncertainty. A known ceiling for an unknown one.

It is too early to say whether it was the right call. But I know this: the version of me that stayed would have been smaller. And I would rather fail at something that matters than succeed at something that does not.`,
  },
];
