export interface Essay {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  content: string;
}

export const essays: Essay[] = [
  {
    id: "ai-didnt-break-literacy",
    title: "AI Didn't Break Literacy, We Did",
    excerpt: "Long before ChatGPT entered classrooms, literacy was already in decline. The tools simply revealed the fractures already there.",
    date: "Apr 2026",
    readTime: "12 min",
    content: `In 2026, students use AI voraciously. But long before ChatGPT entered classrooms, literacy was already in decline.

When I ran a tutoring company with over 500 students, I saw nine-year-olds submit writing homework entirely generated by AI. Parents could not believe their children knew how to use AI, and students, for the most part, felt clever. But what I saw beneath the surface was not an AI problem, it was a literacy one. The tools simply revealed the fractures already there.

Do Not Blame the Robots

AI may be a convenient scapegoat, but it does not explain the data. In 2022, only 26% of U.S. eighth graders were proficient in writing, based on a national assessment last conducted in 2011. Reading scores have been falling steadily for more than a decade. The truth is, we lost our grip on literacy long before students had access to chatbots.

What Is Really Going On

The underlying causes are complex:

• Children are immersed in an attention economy. Reading and writing compete with infinite scroll platforms optimised for compulsive interaction. Between TikTok, Roblox and YouTube Shorts, sustained engagement with complex ideas is increasingly rare.
• Students are exposed primarily to short-form, low-complexity inputs such as captions, comments, scripts and chat. The result is a constriction of syntax, reduced lexical diversity and a weakening of abstract reasoning.
• Assigned reading is often avoided. Students outsource comprehension to summaries or AI tools. If the work is not meaningful or connected to their world, there is no intrinsic reason to persist through cognitive friction.

The Cost of Letting It Slide

When students stop reading deeply and writing critically, the downstream effects accumulate:

• They struggle to form, retain and articulate complex thought.
• They become passive consumers in systems that reward clarity and synthesis.
• They hit a glass ceiling they cannot describe because they lack the linguistic tools to name it.
• They grow increasingly reliant on generative systems to scaffold expression, leading to convergence on median linguistic forms controlled by a few foundational models.

AI as a Normalisation Engine

Generative models, by design, predict the most statistically likely output. In doing so, they flatten originality. Students who depend on AI to write are not developing fluency. They are curating from averages. This results in stylistic homogenisation and a diminished capacity to reason beyond the frame of the prompt.

Why Writing Still Matters in the Age of AI

Writing is not just transcription. It is the act of thinking on the page. It forces synthesis, prioritisation and judgment. Even in a world where LLMs draft fluid text, those who write well will retain an edge. They will know how to shape a prompt, how to iterate and how to decide what is worth saying. Writing is not obsolete. It is becoming a meta-skill.

Reclaiming Literacy in the Attention Economy

We do not need more gamification. We need more meaning.
Real engagement is not built on dopamine loops. It is built on relevance.
That means designing literacy experiences that connect to students' interests and communities, and then stretch them into complexity. Personal expression, authentic audience and voice are not luxuries. They are the gateway to deeper learning.

Rethinking Assessment for a Post-AI World

Assessments shape habits. If we want original thinkers, we must assign tasks that cannot be easily completed by language models. These include:

• Context-rich writing grounded in personal experience
• Open-ended argumentation with unpredictable structure
• Projects that reward novelty, ambiguity and divergent thinking

When AI is useful, such as for planning, ideation or rephrasing, we should teach students how to use it critically rather than blindly. Not as a replacement, but as a tool to extend their reach.

Rebuilding Writing Instruction at Scale

Writing is cognitively demanding. It is slow, recursive and difficult to standardise. This is why it was sidelined during pandemic-era instruction in favour of subjects more easily assessed.

But writing is also where reasoning is made visible. We need tools and approaches that:

• Model expert composition processes
• Provide formative feedback on syntax, structure and clarity
• Adapt to diverse entry points and skill levels

Unlike mathematics, English has no single knowledge graph. Diagnostic literacy tools must reflect this by measuring not binary right or wrong answers, but gradients of progress in coherence, argument and rhetorical control.

Defining Literacy for 2030

Literacy now includes:

• Deep reading and critical consumption of generated content
• Generative fluency, meaning the ability to collaborate with AI without ceding authorship
• Writing with clarity, originality and audience awareness in a hybrid human–machine world

These are not skills we can afford to leave undeveloped.

The Path Forward

Blaming AI for a crisis it did not create obscures what really happened.
We let literacy drift. We stripped it of purpose, pressure-tested it under outdated metrics and failed to connect it to the world students actually live in.

If we want a generation that can think clearly, argue with nuance and write with power, we must treat literacy not as a subject but as infrastructure.
Because reclaiming literacy is not about resisting technology.
It is about remembering why writing ever mattered in the first place.`,
  },
  {
    id: "buying-my-second-house-at-19",
    title: "Buying My Second House at 19",
    excerpt: "Australian banks need a 10% deposit. I had $1,000. This taught me to test assumptions and push relentlessly.",
    date: "Mar 2026",
    readTime: "3 min",
    content: `At 19, I bought an $888k house with only $1,000. Australian banks need a 10% deposit, but I found this was a perception issue rather than a hard rule.

I cold called dozens of solicitors, brokers, and accountants until I found people willing to help me structure the deal so a lender would accept it. Once the support was in place, I was approved on Friday, inspected on Saturday, and signed on Monday.

This taught me to test assumptions and push relentlessly. Most barriers are not walls — they are doors that nobody has tried opening from the right angle.`,
  },
  {
    id: "why-i-decided-to-risk-it-all",
    title: "Why I Decided to Risk It All",
    excerpt: "Leaving a tutoring business doing $500k ARR and selling all property. Sunk cost, the region beta paradox, and choosing growth over comfort.",
    date: "Feb 2026",
    readTime: "4 min",
    content: `I walked away from a tutoring business doing $500k in annual recurring revenue. I sold all my property. From the outside, it looked irrational. From the inside, it was the clearest decision I have ever made.

The sunk cost was real. Years of work, relationships, reputation — all built around a model I had outgrown. But sunk cost is a trap precisely because it feels like value. It is not. It is weight.

There is a concept called the region beta paradox: moderate discomfort is harder to escape than extreme pain, because it never triggers the urgency to change. I was comfortable. The business was growing. I could see the next five years clearly — more tutoring centres, more property, more of the same. And that clarity terrified me. I could not see myself being happy. I could not see myself being more fulfilled.

I realised I was optimising for a life I did not want. The trajectory was legible, stable, and completely uninspiring. I was bored — not in the shallow sense, but in the deep sense of knowing that I was capable of more and choosing not to pursue it.

So I made the trade. Security for growth. Comfort for uncertainty. A known ceiling for an unknown one. I wanted to build things at a larger scale. I wanted to work on problems that stretched me, not ones I had already solved.

It is too early to say whether it was the right call. But I know this: the version of me that stayed would have been smaller. And I would rather fail at something that matters than succeed at something that does not.`,
  },
];
